### ISSUE TITLE
[bug] Error: w3m-account-view: No account provided

### ISSUE THREAD

**Issue by nobita851** [WalletConnect/web3modal#1463]
### Link to minimal reproducible example

https://github.com/WalletConnect/web3modal/tree/V3/examples/react-ethers5

### Summary

When using `@web3modal/ethers5: ^3.2.0`, switching between different chains throws `Error: w3m-account-view: No account provided`.
I also tried with [examples](https://github.com/WalletConnect/web3modal/tree/V3/examples/react-ethers5) repository and the issue persisted.
Attaching a screenshot of examples-repo running on my local.
![image](https://github.com/WalletConnect/web3modal/assets/54791621/ec69928f-9b7f-459f-81db-5f7986578632)

### List of related npm package versions

```
  "dependencies": {
    "@web3modal/ethers5": "3.2.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "4.1.0"
  }
  ```

**Comment by glitch-txs** [comment]
You can test this in labs https://lab.web3modal.com/library/ethers/

Could you share the steps to reproduce the issue?

**Comment by nobita851** [comment]
> You can test this in labs https://lab.web3modal.com/library/ethers/
> 
> Could you share the steps to reproduce the issue?

After connecting the wallet (I tried with Metamask), try switching between different networks. The connect wallet button switches to a spinner which keeps buffering.

**Comment by glitch-txs** [comment]
I was able to reproduce it, could you take a look @svenvoskamp ?

**Comment by svenvoskamp** [comment]
This issue has been resolved, so closing this one.

**Comment by oxy-Op** [comment]
> This issue has been resolved, so closing this one.

I am using the latest version @3.5.1, but this same bug still persists

**Comment by PaDuckk** [comment]
> > This issue has been resolved, so closing this one.
> 
> I am using the latest version @3.5.1 in react, but this same bug still persists

me too

3.5.7 same

**Comment by glitch-txs** [comment]
latest is 4.1.0
