### ISSUE TITLE
[bug] 1st time connect Coinbase to mantle(chain), click "Connect" shows "Connection declined"

### ISSUE THREAD

**Issue by lyfmantle** [WalletConnect/web3modal#2125]
### Link to minimal reproducible example

https://stackblitz.com/edit/web3modal-next-template-1fsbqj

### Summary

But after click "Try again", it will be connected

reproducible demo: https://stackblitz.com/edit/web3modal-next-template-1fsbqj

### List of related npm package versions

"@web3modal/wagmi": "4.1.6"

**Comment by glitch-txs** [comment]
Hi, could you update to the latest version? this should be fixed now

**Comment by lyfmantle** [comment]
hi, I upgraded to the latest version `@web3modal/wagmi@4.1.6`, and the problem is still exist
https://stackblitz.com/edit/web3modal-next-template-1fsbqj?file=package.json

**Comment by glitch-txs** [comment]
Could you share the steps to reproduce it? It was working well on our end

**Comment by lyfmantle** [comment]
it must be the 1st time connect Coinbase to mantle(chain), if not 1st time, should disconnect and refresh the page.

1. click "Connect" in the Coinbase extension popup
2. actually it's connected in the extension popup
3. but web3modal shows "Connection declined"
4. after click "try again", it will be connected

only exists when connect to the mantle chain, if connect to the mainnet, it won't happen,
my hope is to not show the "Connection declined" error.

![1](https://github.com/WalletConnect/web3modal/assets/161433628/edab3011-acfa-4056-bc2c-983847119527)
![2](https://github.com/WalletConnect/web3modal/assets/161433628/20baf597-b98e-471b-ab59-ffc961c3df75)

**Comment by glitch-txs** [comment]
Should be fixed on the latest
