### ISSUE TITLE
Beta.4-5 breaking changes & full wagmi support

### ISSUE THREAD

**Issue by IljaDaderko** [WalletConnect/web3modal#702]
Hi everyone, we have released beta.4 which under the hood gets rid of our custom react hooks and controllers and instead provides full support for https://wagmi.sh

Wagmi is a great library that we were already using before, but were not able to provide full integration for until now.

## React
Please follow [updated documentation](https://docs.walletconnect.com/2.0/introduction/web3modal/about) to see how to set up web3modal with wagmi.

Once integrated, you will need to replace all `@web3modal/react` hooks with ones from `wagmi`. See [Wagmi Documentation](https://wagmi.sh) for all available options. In general this should bring you way more stability and allow to use other wagmi compatible libraries like [lens-use](https://github.com/memester-xyz/lens-use) for example.

## HTML / JS
Similar to how react no longer has hooks, vanilla no longer uses controllers. Instead you can import and use core functions like `getAccount` / `watchAccount` / `getSigner` etc. from `@wagmi/core` package. See updated [example](https://github.com/WalletConnect/web3modal/tree/V2/examples/html ) for new integration steps.

We are working with wagmi team to document `@wagmi/core` lib, but meanwhile feel free to ask questions here and use your editors intelisens / typescript autocompletion to see what is available.

Feel free to use this issue for further questions.

**Comment by M4cs** [comment]
modalConnectors() is not working with the connectors argument in createClient for wagmi. When trying to do so it's getting a type error. See below:
<img width="983" alt="image" src="https://user-images.githubusercontent.com/34947910/202061455-877eef3d-5fe0-4028-aa7c-6cb85df9916d.png">

Anyway around this?

**Comment by nhardy** [comment]
I've noticed that this can break in subtle ways if the version of `@wagmi/core` depended on by `wagmi` is mismatched when compared to the version used by `@web3modal/ethereum` and can't be deduped by npm.
Wondering if this could be resolved by adding `@wagmi/core` to `peerDependencies` instead of it being a direct dependency?

**Comment by IljaDaderko** [comment]
@nhardy will look into this 👍 @M4cs Could you update `wagmi` to lates version (if you haven't done so already). There were some breaking changes there and we are using their latest `wagmi/core` lib

**Comment by IljaDaderko** [comment]
Inconsistencies between versions will be solved in upcoming beta.5 ^

**Comment by IljaDaderko** [comment]
@timefordroids `(possible exports: Web3ModalEthereum)` this looks like you might be still using an older version i.e. you don't have access to new imports, but do have access to older ones.

Make sure all packages are on `beta.5` (fastest way to ensure this is to delete your `.lock` file and `node_modules` and just re-install everything fresh)

**Comment by timefordroids** [comment]
All the packages were installed in a first-time. 
That's what I have in yarn.lock
```
"@web3modal/core@npm:2.0.0-fbf9251":
  version: 2.0.0-fbf9251
  resolution: "@web3modal/core@npm:2.0.0-fbf9251"
  dependencies:
    valtio: 1.7.0
  peerDependencies:
    "@web3modal/ethereum": "*"
  peerDependenciesMeta:
    "@web3modal/ethereum":
      optional: true
  checksum: b23314261129c8d76b26d27805f4658892cf3fbecc0f179a6989dad9bf31a4dd3f4dc51ac007e8b6859fca14499dc70f90ae3a63c7f980fb2ff36e3dc2d8f728
  languageName: node
  linkType: hard

"@web3modal/ethereum@npm:^2.0.0-beta.5":
  version: 2.0.0-fbf9251
  resolution: "@web3modal/ethereum@npm:2.0.0-fbf9251"
  dependencies:
    "@coinbase/wallet-sdk": 3.5.2
    "@walletconnect/ethereum-provider": 1.8.0
  peerDependencies:
    "@wagmi/core": ">=0.5.x"
    "@web3modal/core": "*"
  checksum: 4e76813c390ea9c0c8117f8bdd88621713a1d5df4c57157944a7cf48865715622c31356f32844a60902a9b4c2b14879ac93666fe2b33677a507218e0d657a113
  languageName: node
  linkType: hard

"@web3modal/react@npm:^2.0.0-beta.5":
  version: 2.0.0-fbf9251
  resolution: "@web3modal/react@npm:2.0.0-fbf9251"
  dependencies:
    "@web3modal/core": 2.0.0-fbf9251
    "@web3modal/ui": 2.0.0-fbf9251
  peerDependencies:
    react: ">=17.x"
    react-dom: ">=17.x"
  checksum: 8fee528e925f9e4bfeec39c2ced7c516b4e527557fcc6d1e6256a6e7c48bb436b5713ab6b1ffd048f035d44115596384fe7e233365c0bbfdc4a4cee6868c5e8f
  languageName: node
  linkType: hard
```

**Comment by IljaDaderko** [comment]
@timefordroids Hmm that core version looks incorrect, should also be beta.5 not `2.0.0-fbf9251`

**Comment by timefordroids** [comment]
Just added the exact version of core (2.0.0-beta.5) to package.json and it works now. Thank you.

**Comment by IljaDaderko** [comment]
@timefordroids nice, although, you can probably remove it now as core package is part of react one.

**Comment by inartin** [comment]
Can someone pls give me a hint what's wrong here?

I did a bundle using browserify to use it in vanilla js without modules (can't use modules in my specific use case)

at the "createClien" step, it throws this error:

```
bundle_beta5.js:12295 Uncaught TypeError: Class constructor Provider cannot be invoked without 'new'
    at StaticJsonRpcProvider.BaseProvider [as constructor]
```

Here is the code from bundle at the 12295 line

<img width="397" alt="Screenshot 2022-11-16 at 18 25 22" src="https://user-images.githubusercontent.com/17723007/202236787-9513a2eb-6306-471a-a7ab-939438ad6bdf.png">


I keep getting this error even before beta 4.

What am I missing?

**Comment by M4cs** [comment]
> @nhardy will look into this 👍 @M4cs Could you update `wagmi` to lates version (if you haven't done so already). There were some breaking changes there and we are using their latest `wagmi/core` lib

Fwiw using `wagmi@0.8.3` fixed my issue with beta 4 but beta 5 with newest wagmi works 👍

**Comment by IljaDaderko** [comment]
Yep, any wagmi 0.8.x version should be working starting with beta 5 👌

**Comment by IljaDaderko** [comment]
Closing this in favour of beta.6 issue
https://github.com/WalletConnect/web3modal/issues/729

**Comment by archae0pteryx** [comment]
FWIW, following the latest docs, i am still not finding the walletConnectProvidor export from @web3modal/ethereum. Neither with beta.5 or beta.7

**Comment by IljaDaderko** [comment]
@archae0pteryx Should definetely be there on beta.7

We use it in all our examples i.e here it is in react
https://github.com/WalletConnect/web3modal/blob/V2/examples/react/src/pages/_app.tsx#L1

Above example deploys here
https://web3modal-dev.pages.dev
